@startuml

   App1 -> Hub: send Patient-open
   Hub -> App2++: send Patient-open
   Hub <-- App2--: 409 Conflict
   Hub -> App1++: send Patient-open
   Hub <-- App1--: 200 OK
   Hub -> App1: send syncerror
   Hub -> App2: send syncerror
   
@enduml
