@startuml

App1 -> Hub: send Patient-open
Hub -> App2++: send Patient-open
Hub <-- App2--: 202 Accepted
Hub -> App1++: send Patient-open
Hub <-- App1--: 200 OK
App2 -> Hub: send syncerror
Hub -> App1: send syncerror
Hub -> App2: send syncerror

@enduml