
@startuml

  participant App
  participant Hub

  loop send heartbeat
    Hub -> App: send heartbeat
  end loop

  note over App : App looses connection
  note over App : App detects heartbeat is not send
  note left of App : syncerror

@enduml