@startuml
    actor Clinician
    participant "EHR App\n(Subscriber)" as EHR
    participant "Reporting\nApplication\n(Subscriber)" as RepApp
    participant Hub
    participant "Image Reading\nApplication\n(Subscriber)" as App1
    participant "Advanced\nQuantification\nApplication\n(Subscriber)" as App2
    
    Clinician -> App1: 1: Open Advanced Quantification Application
    App1 -> App2++: 2: Open with FHIRcast Topic
    App2 -> Hub: 3: Subscribe to Topic
    App2 -> Hub: 4: Get Current Context (includes existing content if any)
    note over App2: 5: Adjust to Context\n and store versionId
    deactivate App2
    
    Clinician -> App2: 6: Generate finding
    App2 -\ Hub++: 7: DiagnosticReport-update with versionId
    note over Hub
        8: update Content
        and Generate new versionId
    end note
    Hub -\ EHR: 9a DiagnosticReport-update with\nVersiondId and priorversionId
    note over EHR: 10: ignore
    Hub -\ App1: 9b: DiagnosticReport-update with\nVersiondId and priorversionId
    note over App1: 11: Update Content\n and store versionId
    Hub -\ RepApp: 9c: DiagnosticReport-update with\nVersiondId and priorversionId
    note over RepApp: 12: Update Content\n and store versionId
    Hub -\ App2: 9d: DiagnosticReport-update with\nVersiondId and priorversionId
    note over App2: 13: store versionId
    deactivate Hub
@enduml

