@startuml
    actor Clinician
    participant "EHR App\n(Subscriber)" as EHR
    participant "Reporting\nApplication\n(Subscriber)" as RepApp
    participant Hub
    participant "Image Reading\nApplication\n(Subscriber)" as App1
    
    Clinician -> App1: 1: make measurement
    App1 -> Hub++: 2: DiagnosticReport-update\nwith VersionId

    group Validate Update Request
    else versionId incorrect
        Hub --> App1:2: Reject DiagnosticReport-update
    else VersionId correct
        note over Hub: 3: Update Content \nand generate new VersionId
        Hub -\ EHR: 4a: DiagnosticReport-update with VersionId\nand priorVersionId
        note over EHR: 5: ignore
        Hub -\ App1: 4b: DiagnosticReport-update with VersionId\nand priorVersionId
        note over App1: 6: store VersionId
        Hub -\ RepApp: 4c:DiagnosticReport-update with VersionId\nand priorVersionId
        group Validate Current Version
        else priorVersion Correct
            note over RepApp: 7: update Content and\nstore VersionId
        else priorVersion Incorrect
            RepApp -> Hub: 8: Get Current Context
        end
    end

    Clinician -> RepApp: 9: Select a Measurement
    RepApp -> Hub: 10: DiagnosticReport-select
    Hub -\ EHR: 11a: DiagnosticReport-select
        note over EHR: 12: ignore
    Hub -\ App1: 11b: DiagnosticReport-select
    note over App1: 13: Adjust UI
    Hub -\ RepApp: 11c: DiagnosticReport-select

@enduml

