@startuml

title Successfull Websocket subscription flow diagram

participant "App\n(Subscriber)" as Subscriber
participant "FHIRcast\nHub" as Hub

Subscriber -> Hub++: POST Suscribe
Subscriber <-- Hub--: 202 Accepted [<wss URL>]
Subscriber -> Hub: connect to <wss URL>>
Subscriber <-- Hub: WSS: conformation

note right of Hub
    App Subscribes
    to Hub. Hub creates a websocket
    and confirms subscription once 
    app connects.
end note

Hub --> Subscriber++: WS: denial

@enduml